language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls pytest-cov pytest-pep8
script:
  - py.test test_lamium.py --cov lamium --pep8
after_success:
  - coveralls

